name: ExilityBans
version: 1.0
main: me.exility.bans.ExilityBans
api-version: 1.21

commands:
  ban:
    description: Banir permanentemente
    permission: exility.ban
  tempban:
    description: Banir temporariamente
    permission: exility.tempban
  unban:
    description: Desbanir jogador
    permission: exility.unban
